// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katz.taskmanager.model;

import com.katz.taskmanager.model.Task;

privileged aspect Task_Roo_JavaBean {
    
    public String Task.getDescription() {
        return this.description;
    }
    
    public void Task.setDescription(String description) {
        this.description = description;
    }
    
}
